# Generated by Django 5.2.7 on 2026-01-17 01:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('check_in_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='attsys.event')),
            ],
            options={
                'ordering': ['-attended_at'],
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, verbose_name='Course Applied')),
                ('college', models.CharField(max_length=200, verbose_name='College/Branch')),
                ('register_date', models.DateField(verbose_name='Registration Date')),
                ('pre_registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pre-Registration Fee (RM)')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Registration Fee (RM)')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10, verbose_name='Payment Status (Registration Fee)')),
                ('remark', models.TextField(blank=True, verbose_name='Staff Remarks')),
                ('closer', models.CharField(max_length=100, verbose_name='Closer (Staff Name)')),
                ('referral_number', models.CharField(blank=True, max_length=50, verbose_name='Referral Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='attsys.attendee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_officer', models.CharField(max_length=150)),
                ('applied_programme', models.CharField(choices=[('Diploma', 'Diploma'), ('Pra-Diploma', 'Pra-Diploma'), ('TVET', 'TVET'), ('Smart Tahfiz', 'Smart Tahfiz')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('ic_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('marriage_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10)),
                ('father_name', models.CharField(max_length=150)),
                ('father_ic', models.CharField(max_length=20)),
                ('father_phone', models.CharField(max_length=15)),
                ('father_occupation', models.CharField(blank=True, max_length=150)),
                ('father_income', models.CharField(blank=True, max_length=50)),
                ('father_dependants', models.PositiveSmallIntegerField(default=0)),
                ('mother_name', models.CharField(max_length=150)),
                ('mother_ic', models.CharField(max_length=20)),
                ('mother_phone', models.CharField(max_length=15)),
                ('mother_occupation', models.CharField(blank=True, max_length=150)),
                ('mother_income', models.CharField(blank=True, max_length=50)),
                ('mother_dependants', models.PositiveSmallIntegerField(default=0)),
                ('interested_programme', models.TextField(blank=True)),
                ('interest_choice1', models.TextField(blank=True, verbose_name='First Choice Programme')),
                ('interest_choice2', models.TextField(blank=True, verbose_name='Second Choice Programme')),
                ('interest_choice3', models.TextField(blank=True, verbose_name='Other Programme Interests')),
                ('spm_total_credit', models.PositiveSmallIntegerField(default=0, help_text='Total credit from SPM results', verbose_name='Total SPM Credit')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='attsys.event')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('event', 'ic_no')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='attsys.event')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
