# Generated by Django 5.2.7 on 2025-12-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='qr_token',
        ),
        migrations.AddField(
            model_name='event',
            name='check_in_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
