# Generated by Django 5.2.10 on 2026-01-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='registration_officer',
            field=models.CharField(max_length=150, verbose_name='Inviting Officer'),
        ),
    ]
