# Generated by Django 5.2.7 on 2025-12-23 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0003_event_assigned_staff_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='check_in_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_speaker', models.CharField(max_length=150)),
                ('applied_programme', models.CharField(choices=[('Diploma', 'Diploma'), ('Pra-Diploma', 'Pra-Diploma'), ('TVET', 'TVET'), ('Smart Tahfiz', 'Smart Tahfiz')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('ic_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('marriage_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10)),
                ('father_name', models.CharField(max_length=150)),
                ('father_ic', models.CharField(max_length=20)),
                ('father_phone', models.CharField(max_length=15)),
                ('father_occupation', models.CharField(blank=True, max_length=150)),
                ('father_income', models.CharField(blank=True, max_length=50)),
                ('father_dependants', models.PositiveSmallIntegerField(default=0)),
                ('mother_name', models.CharField(max_length=150)),
                ('mother_ic', models.CharField(max_length=20)),
                ('mother_phone', models.CharField(max_length=15)),
                ('mother_occupation', models.CharField(blank=True, max_length=150)),
                ('mother_income', models.CharField(blank=True, max_length=50)),
                ('mother_dependants', models.PositiveSmallIntegerField(default=0)),
                ('interested_programme', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='attsys.event')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('event', 'ic_no')},
            },
        ),
    ]
