# Generated by Django 5.2.10 on 2026-01-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0003_alter_application_registration_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address2',
        ),
    ]
