# Generated by Django 5.2.10 on 2026-01-24 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0004_remove_application_address2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['-attended_at'], 'verbose_name': 'Attendee', 'verbose_name_plural': 'Attendees'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AddField(
            model_name='application',
            name='address2',
            field=models.TextField(blank=True, verbose_name='Address Line 2 (Optional)'),
        ),
        migrations.AddField(
            model_name='application',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
        ),
        migrations.AddField(
            model_name='application',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Approval Notes'),
        ),
        migrations.AddField(
            model_name='application',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='career_aspirations',
            field=models.TextField(blank=True, verbose_name='Career Aspirations'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_course',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current Course'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current School/College'),
        ),
        migrations.AddField(
            model_name='application',
            name='custom_programme',
            field=models.CharField(blank=True, help_text="Specify if 'Other Programme' is selected", max_length=200, verbose_name='Other Programme (if selected)'),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Graduation Date'),
        ),
        migrations.AddField(
            model_name='application',
            name='father_employer',
            field=models.CharField(blank=True, max_length=200, verbose_name="Father's Employer"),
        ),
        migrations.AddField(
            model_name='application',
            name='father_office_address',
            field=models.TextField(blank=True, verbose_name="Father's Office Address"),
        ),
        migrations.AddField(
            model_name='application',
            name='father_office_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name="Father's Office Phone"),
        ),
        migrations.AddField(
            model_name='application',
            name='how_did_you_hear',
            field=models.CharField(blank=True, help_text='e.g., Friend, Social Media, Newspaper, etc.', max_length=200, verbose_name='How did you hear about us?'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Application Approved'),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_employer',
            field=models.CharField(blank=True, max_length=200, verbose_name="Mother's Employer"),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_office_address',
            field=models.TextField(blank=True, verbose_name="Mother's Office Address"),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_office_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name="Mother's Office Phone"),
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(default='Malaysian', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_education',
            field=models.TextField(blank=True, verbose_name='Previous Education Background'),
        ),
        migrations.AddField(
            model_name='application',
            name='race',
            field=models.CharField(blank=True, max_length=50, verbose_name='Race'),
        ),
        migrations.AddField(
            model_name='application',
            name='religion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='application',
            name='special_needs',
            field=models.TextField(blank=True, help_text='Any special accommodations needed', verbose_name='Special Needs/Requirements'),
        ),
        migrations.AddField(
            model_name='application',
            name='spm_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SPM Year'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='checkin_method',
            field=models.CharField(choices=[('QR', 'QR Code Scan'), ('MANUAL', 'Manual Entry'), ('API', 'API Integration')], default='QR', max_length=10, verbose_name='Check-in Method'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='institution',
            field=models.CharField(blank=True, max_length=200, verbose_name='School/Institution'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Verified Check-in'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Staff Notes'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student/Matric ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_state',
            field=models.CharField(blank=True, help_text="Specify state if 'Other' is selected above", max_length=100, verbose_name='Other State (if selected)'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('KUALA_LUMPUR', 'Kuala Lumpur'), ('SELANGOR', 'Selangor'), ('JOHOR', 'Johor'), ('PENANG', 'Penang'), ('PERAK', 'Perak'), ('SABAH', 'Sabah'), ('SARAWAK', 'Sarawak'), ('PAHANG', 'Pahang'), ('NEGERI_SEMBILAN', 'Negeri Sembilan'), ('KEDAH', 'Kedah'), ('KELANTAN', 'Kelantan'), ('TERENGGANU', 'Terengganu'), ('MELAKA', 'Melaka'), ('PERLIS', 'Perlis'), ('LABUAN', 'Labuan'), ('PUTRAJAYA', 'Putrajaya'), ('OTHER', 'Other')], default='KUALA_LUMPUR', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='allow_contact',
            field=models.BooleanField(default=False, verbose_name='I agree to be contacted for follow-up'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='best_part',
            field=models.TextField(blank=True, verbose_name='What was the best part of the event?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('EVENT', 'Event Overall'), ('VENUE', 'Venue/Facilities'), ('CONTENT', 'Content/Program'), ('SPEAKERS', 'Speakers/Presenters'), ('ORGANIZATION', 'Organization'), ('OTHER', 'Other')], default='EVENT', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='improvements_suggested',
            field=models.TextField(blank=True, verbose_name='Suggestions for Improvement'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='would_recommend',
            field=models.BooleanField(default=True, verbose_name='Would you recommend this event to others?'),
        ),
        migrations.AddField(
            model_name='registration',
            name='campus',
            field=models.CharField(blank=True, max_length=100, verbose_name='Campus/Location'),
        ),
        migrations.AddField(
            model_name='registration',
            name='closer_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Closer Staff ID'),
        ),
        migrations.AddField(
            model_name='registration',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='registration',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='registration',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount (RM)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='discount_reason',
            field=models.TextField(blank=True, verbose_name='Discount Reason/Code'),
        ),
        migrations.AddField(
            model_name='registration',
            name='hostel_required',
            field=models.BooleanField(default=False, verbose_name='Requires Hostel Accommodation'),
        ),
        migrations.AddField(
            model_name='registration',
            name='intake_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Intake Period'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Registration Verified'),
        ),
        migrations.AddField(
            model_name='registration',
            name='material_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Material Fee (RM)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Other Fees (RM)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('ONLINE', 'Online Payment'), ('OTHER', 'Other')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Reference/Transaction ID'),
        ),
        migrations.AddField(
            model_name='registration',
            name='scholarship_applied',
            field=models.BooleanField(default=False, verbose_name='Applied for Scholarship'),
        ),
        migrations.AddField(
            model_name='registration',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Scholarship Type'),
        ),
        migrations.AddField(
            model_name='registration',
            name='study_mode',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('DISTANCE', 'Distance Learning'), ('ONLINE', 'Online')], default='FULL_TIME', max_length=20, verbose_name='Study Mode'),
        ),
        migrations.AddField(
            model_name='registration',
            name='transportation_required',
            field=models.BooleanField(default=False, verbose_name='Requires Transportation'),
        ),
        migrations.AddField(
            model_name='registration',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Date'),
        ),
        migrations.AddField(
            model_name='registration',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Verification Notes'),
        ),
        migrations.AddField(
            model_name='registration',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='address1',
            field=models.TextField(verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applied_programme',
            field=models.CharField(choices=[('DIPLOMA', 'Diploma'), ('PRA_DIPLOMA', 'Pra-Diploma'), ('TVET', 'TVET'), ('SMART_TAHFIZ', 'Smart Tahfiz'), ('OTHER', 'Other Programme')], default='DIPLOMA', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_dependants',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of Dependants'),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_ic',
            field=models.CharField(max_length=20, verbose_name="Father's IC Number"),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_income',
            field=models.CharField(blank=True, max_length=50, verbose_name="Father's Monthly Income (RM)"),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_name',
            field=models.CharField(max_length=150, verbose_name="Father's Full Name"),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=150, verbose_name="Father's Occupation"),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_phone',
            field=models.CharField(max_length=15, verbose_name="Father's Phone Number"),
        ),
        migrations.AlterField(
            model_name='application',
            name='ic_no',
            field=models.CharField(max_length=20, verbose_name='IC Number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_choice1',
            field=models.TextField(blank=True, help_text='Your primary programme of interest', verbose_name='First Choice Programme'),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_choice2',
            field=models.TextField(blank=True, help_text='Your secondary programme of interest', verbose_name='Second Choice Programme'),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_choice3',
            field=models.TextField(blank=True, help_text="Any other programmes you're interested in", verbose_name='Other Programme Interests'),
        ),
        migrations.AlterField(
            model_name='application',
            name='interested_programme',
            field=models.TextField(blank=True, help_text='Auto-generated from choices above', verbose_name='Programme Interests (Legacy)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='marriage_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_dependants',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of Dependants'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_ic',
            field=models.CharField(max_length=20, verbose_name="Mother's IC Number"),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_income',
            field=models.CharField(blank=True, max_length=50, verbose_name="Mother's Monthly Income (RM)"),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_name',
            field=models.CharField(max_length=150, verbose_name="Mother's Full Name"),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=150, verbose_name="Mother's Occupation"),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_phone',
            field=models.CharField(max_length=15, verbose_name="Mother's Phone Number"),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_no',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='registration_officer',
            field=models.CharField(max_length=150, verbose_name='Inviting Officer/Referral'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ Very Poor'), (2, '⭐⭐ Poor'), (3, '⭐⭐⭐ Average'), (4, '⭐⭐⭐⭐ Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], default=3),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID_PARTIAL', 'Paid Partial'), ('PAID_FULL', 'Paid Full'), ('OVERPAID', 'Overpaid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('DONE', 'Completed')], default='PENDING', max_length=15, verbose_name='Payment Status'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['event', 'submitted_at'], name='attsys_appl_event_i_d7a270_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['ic_no'], name='attsys_appl_ic_no_18c819_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='attsys_appl_email_52e005_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['event', 'attended_at'], name='attsys_atte_event_i_96502c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['email'], name='attsys_atte_email_3433ba_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['event', 'submitted_at'], name='attsys_feed_event_i_3731a2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='attsys_feed_rating_70e177_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['attendee'], name='attsys_regi_attende_a3335a_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['payment_status'], name='attsys_regi_payment_c72d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['register_date'], name='attsys_regi_registe_477f56_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['closer'], name='attsys_regi_closer_2b74d1_idx'),
        ),
    ]
