# Generated by Django 5.2.7 on 2026-01-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0004_alter_event_check_in_token_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='invited_speaker',
            new_name='registration_officer',
        ),
    ]
