# Generated by Django 5.2.10 on 2026-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0005_alter_application_options_alter_attendee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='event',
            name='custom_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other State'),
        ),
    ]
