# Generated by Django 5.2.7 on 2026-01-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0005_rename_invited_speaker_application_registration_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interest_choice1',
            field=models.TextField(blank=True, verbose_name='First Choice Programme'),
        ),
        migrations.AddField(
            model_name='application',
            name='interest_choice2',
            field=models.TextField(blank=True, verbose_name='Second Choice Programme'),
        ),
        migrations.AddField(
            model_name='application',
            name='interest_choice3',
            field=models.TextField(blank=True, verbose_name='Other Programme Interests'),
        ),
        migrations.AddField(
            model_name='application',
            name='spm_total_credit',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total credit from SPM results', verbose_name='Total SPM Credit'),
        ),
    ]
