# Generated by Django 5.2.7 on 2026-01-16 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0006_application_interest_choice1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, verbose_name='Course Applied')),
                ('college', models.CharField(max_length=200, verbose_name='College/Branch')),
                ('register_date', models.DateField(verbose_name='Registration Date')),
                ('pre_registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pre-Registration Fee (RM)')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Registration Fee (RM)')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10, verbose_name='Payment Status (Registration Fee)')),
                ('remark', models.TextField(blank=True, verbose_name='Staff Remarks')),
                ('closer', models.CharField(max_length=100, verbose_name='Closer (Staff Name)')),
                ('referral_number', models.CharField(blank=True, max_length=50, verbose_name='Referral Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='attsys.attendee')),
            ],
        ),
    ]
