# Generated by Django 5.2.10 on 2026-01-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0006_alter_event_options_alter_event_custom_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('print_count', models.IntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_records', to='attsys.application')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
    ]
