# Generated by Django 5.2.10 on 2026-01-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0007_printrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attended_with',
            field=models.CharField(choices=[('PARENT', 'With Parent(s)'), ('GUARDIAN', 'With Guardian')], default='PARENT', max_length=20, verbose_name='Attended With'),
        ),
    ]
