# Generated by Django 5.2.7 on 2026-01-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0007_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='registration',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_info', to='attsys.attendee'),
        ),
    ]
