# Generated by Django 5.2.7 on 2026-01-16 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0008_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='attsys.attendee'),
        ),
    ]
