# Generated by Django 5.2.10 on 2026-01-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0008_application_attended_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='mother_dependants',
        ),
    ]
