# Generated by Django 5.2.10 on 2026-01-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0009_remove_application_mother_dependants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='registration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid (RM)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ONLINE_BANKING', 'Online Banking'), ('QR_PAYMENT', 'QR Payment')], max_length=20, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applied_programme',
            field=models.CharField(choices=[('DIPLOMA', 'Diploma'), ('PRA_DIPLOMA', 'Pra-Diploma'), ('TVET', 'TVET'), ('SMART_TAHFIZ', 'Smart Tahfiz')], default='DIPLOMA', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='marriage_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('DONE', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15, verbose_name='Payment Status'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['payment_type'], name='attsys_regi_payment_84cc1f_idx'),
        ),
    ]
