# Generated by Django 5.2.10 on 2026-02-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0010_remove_application_address2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
