# Generated by Django 5.2.10 on 2026-02-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0011_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ Very Poor'), (2, '⭐⭐ Poor'), (3, '⭐⭐⭐ Average'), (4, '⭐⭐⭐⭐ Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], default=3)),
                ('category', models.CharField(choices=[('EVENT', 'Event Overall'), ('VENUE', 'Venue/Facilities'), ('CONTENT', 'Content/Program'), ('SPEAKERS', 'Speakers/Presenters'), ('ORGANIZATION', 'Organization'), ('OTHER', 'Other')], default='EVENT', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Would you recommend this event to others?')),
                ('improvements_suggested', models.TextField(blank=True, verbose_name='Suggestions for Improvement')),
                ('best_part', models.TextField(blank=True, verbose_name='What was the best part of the event?')),
                ('allow_contact', models.BooleanField(default=False, verbose_name='I agree to be contacted for follow-up')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='attsys.event')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['event', 'submitted_at'], name='attsys_feed_event_i_3731a2_idx'), models.Index(fields=['rating'], name='attsys_feed_rating_70e177_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
