# Generated by Django 5.2.10 on 2026-02-12 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0012_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printrecord',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='printrecord',
            index=models.Index(fields=['form_number'], name='attsys_prin_form_nu_d5ce8e_idx'),
        ),
        migrations.AddIndex(
            model_name='printrecord',
            index=models.Index(fields=['printed_at'], name='attsys_prin_printed_74587f_idx'),
        ),
    ]
