# Generated by Django 5.2.10 on 2026-02-12 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0013_alter_printrecord_printed_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='printrecord',
            name='attsys_prin_form_nu_d5ce8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='printrecord',
            name='attsys_prin_printed_74587f_idx',
        ),
        migrations.AlterField(
            model_name='printrecord',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
