# Generated by Django 5.2.10 on 2026-02-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attsys', '0014_remove_printrecord_attsys_prin_form_nu_d5ce8e_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
